### ISSUE TITLE
provison of dns controller failled connection refused.

### ISSUE THREAD

**Issue by linearregression** [pires/kubernetes-vagrant-coreos-cluster#220] opened 2016-11-13 17:57 UTC
Pulled latest
Platform windows, using vagrant, k8s :1.44

C:\Users\developer\Documents\GitHub\kubernetes-vagrant-coreos-cluster [(8f3085a...)]> vagrant destroy -
f
==> node-02: VM not created. Moving on...
==> node-01: VM not created. Moving on...
==> master: Forcing shutdown of VM...
==> master: Destroying VM and associated drives...
==> master: Pruning invalid NFS exports.
==> master: Running triggers after destroy...
C:\Users\developer\Documents\GitHub\kubernetes-vagrant-coreos-cluster [(8f3085a...)]> vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
Bringing machine 'node-02' up with 'virtualbox' provider...
==> master: Running triggers before up...
==> master: 2016-11-13 09:43:16 -0800: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.4.3
==> master: Importing base box 'coreos-alpha'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_master_1479059008897_17902
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: core
    master: SSH auth method: private key
==> master: Machine booted and ready!
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Exporting NFS shared folders...
==> master: Preparing to edit nfs mounting file.
[NFS] Status: running
==> master: Mounting NFS shared folders...
==> master: Setting time zone...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Waiting for Kubernetes master to become ready...
==> master: 2016-11-13 09:53:31 -0800: failed to deploy master within timeout count of 50
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master:
==> master: Downloading and installing linux version of 'kubectl' v1.4.3 into /opt/bin. This may take a couple minutes, depending on your internet speed..
==> master: Configuring environment..
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-cluster local --server=http://172.17.8.101:8080 --insecure-skip-tls-verify=true"...
==> master:
==> master: cluster "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-context local --cluster=local --namespace=default"...
==> master:
==> master: context "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config use-context local"...
==> master:
==> master: switched to context "local".
==> master: Remote command execution finished.
==> master: Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/dns-controller.yaml"...
==> master:
==> master: The connection to the server 172.17.8.101:8080 was refused - did you specify the right host or port?
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/dns-controller.yaml" returned a failed exit
code or an exception. The error output is shown below:

The connection to the server 172.17.8.101:8080 was refused - did you specify the right host or port?

**Comment by pires** [comment] 2016-11-15 17:37
> ==> master: Waiting for Kubernetes master to become ready...
==> master: 2016-11-13 09:53:31 -0800: failed to deploy master within timeout count of 50

There's something going on because master is not running.

**Comment by pires** [comment] 2016-11-18 10:55
Can you try now with latest changes in, please?

**Comment by linearregression** [comment] 2016-11-21 01:22
==> master: Downloading and installing linux version of 'kubectl' v1.4.6 into /opt/bin. This may take a couple minutes, depending on your internet speed..
==> master: Configuring environment..
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-cluster default-cluster --server=https://172.17.8.101 --certificate-authority=artifacts/tls/ca.pem"...
==> master:
==> master: cluster "default-cluster" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-credentials default-admin --certificate-authority=artifacts/tls/ca.pem --client-key=artifacts/tls/admin-key.pem --client-certificate=artifacts/tls/admin.pem"...
==> master:
==> master: user "default-admin" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-context local --cluster=default-cluster --user=default-admin"...
==> master:
==> master: context "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config use-context local"...
==> master:
==> master: switched to context "local".
==> master: Remote command execution finished.
==> master: Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/dns-controller.yaml"...
==> master:
==> master: Error in configuration:
==> master: * unable to read client-cert /home/core/artifacts/tls/admin.pem for default-admin due to open /home/core/artifacts/tls/admin.pem: no such file or directory
==> master: * unable to read client-key /home/core/artifacts/tls/admin-key.pem for default-admin due to open /home/core/artifacts/tls/admin-key.pem: no such file or directory
==> master: * unable to read certificate-authority /home/core/artifacts/tls/ca.pem for default-cluster due to open /home/core/artifacts/tls/ca.pem: no such file or directory
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/dns-controller.yaml" returned a failed exit
code or an exception. The error output is shown below:

Error in configuration:
* unable to read client-cert /home/core/artifacts/tls/admin.pem for default-admin due to open /home/core/artifacts/tls/admin.pem: no such file or directory
* unable to read client-key /home/core/artifacts/tls/admin-key.pem for default-admin due to open /home/core/artifacts/tls/admin-key.pem: no such file or directory
* unable to read certificate-authority /home/core/artifacts/tls/ca.pem for default-cluster due to open /home/core/artifacts/tls/ca.pem: no such file or directory

**Comment by pires** [comment] 2016-11-21 13:14
@linearregression can you ssh into your master node and look for `ca.pem`? Something like `sudo find / -name ca.pem` should do the trick.

**Comment by jmwenda** [comment] 2016-12-17 03:39
Hey, also having an error related to this on Ubuntu. Cannot seem to find the admin keys and certs for some reason .. This is when using vagrant up and also when configuring kubernetes dns. Any pointers on what is going wrong. When I ssh to the master, I am able to find ca.pem but not admin.pem. Thanks

==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
Error in configuration: 
* unable to read client-cert /home/core/dev/infrav2/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin.pem for default-admin due to open /home/core/dev/infrav2/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin.pem: no such file or directory
* unable to read client-key /home/core/dev/infrav2/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin-key.pem for default-admin due to open /home/core/dev/infrav2/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin-key.pem: no such file or directory
kubectl already installed in version '1.5.1'. Skipping install.
Configuring environment..
Cluster "default-cluster" set.
User "default-admin" set.
Context "local" set.
Switched to context "local".

**Comment by bukharyi** [comment] 2017-01-06 02:57
I am having the same issue.

**Comment by pires** [comment] 2017-01-06 10:12
@jmwenda @bukharyi read my comment above and provide feedback.

**Comment by nuwandiw** [comment] 2017-02-01 10:47
Hi,
Facing same issue.
Followed the instruction in the comment and here's my result.
```
/etc/kubernetes/ssl/ca.pem
/vagrant/artifacts/tls/ca.pem
find: `/sys/kernel/debug/tracing': No such file or directory
```
Please instruct.

regards

**Comment by pires** [comment] 2017-02-01 11:01
So the files are in place @nuwandiw. Please provide more details, like OS, logs, etc.

**Comment by nuwandiw** [comment] 2017-02-01 14:17
It's searching for a admin.pem it seems. Following shows the result for `kubectl get nodes` command,
```
Error in configuration: 
* unable to read client-cert /home/nuwandi/SUPPORT/QSP/kubernetes_test/pires/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin.pem for default-admin due to open /home/nuwandi/SUPPORT/QSP/kubernetes_test/pires/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin.pem: no such file or directory
* unable to read client-key /home/nuwandi/SUPPORT/QSP/kubernetes_test/pires/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin-key.pem for default-admin due to open /home/nuwandi/SUPPORT/QSP/kubernetes_test/pires/kubernetes-vagrant-coreos-cluster/artifacts/tls/admin-key.pem: no such file or directory
```
attached the log for starting vagrant
[pires_vagrant.txt](https://github.com/pires/kubernetes-vagrant-coreos-cluster/files/745059/pires_vagrant.txt)

**Comment by htesgaard** [comment] 2017-02-02 12:36
I have the same issue. I'm running in Cygwin but experience the same issue if executed inside the regular command prompt,
@pires I'm unable to ssh into master. 
$ ssh master
ssh: connect to host master port 22: Connection timed out

I have added the log with debug information somehow filtered for certain detials:
[vagrant.txt](https://github.com/pires/kubernetes-vagrant-coreos-cluster/files/747700/vagrant.txt)

**Comment by pires** [comment] 2017-02-02 13:00
I can't help because I don't have a Windows system.

**Comment by htesgaard** [comment] 2017-02-02 13:02
Thanks anyway. I have one machine in corporate hell. I will update this if it get it resolved.

**Comment by pires** [comment] 2017-02-10 06:55
#233 should have fixed this, so closing this issue. Please try and comment or re-open if it still fails.

**Closed by pires** 2017-02-10 06:55 UTC
